include:
  - project: 'ifood/pipelines/gitlab-pipelines'
    ref: 'ifood-npm-library-1-stable'
    file: 'pipelines/ifood-npm-library/main.yml'

variables:
  DEFAULT_BUMP_TYPE: 'patch'
  SERVICE_NAME: '@ifood/the-fake-backend'
